categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  0.9.20 of FreeBayes.
long_description: |
  Program: freebayes (Bayesian haplotype-based polymorphism discovery
  and genotyping.)
  Version: 0.9.20 (b040236)
name: package_freebayes_0_9_20_b040236
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/packages/package_freebayes_0_9_20_b040236
type: tool_dependency_definition
