categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  0.0.13 of the fastx toolkit.
long_description: |
  This repository is intended to be defined as a complex repository
  dependency within a separate repository.
  http://wiki.galaxyproject.org/DefiningRepositoryDependencies#Complex_repository_dependencies:_tool_dependency_definitions_that_contain_repository_dependency_definitions
  Program: fastx toolkit
  Version: 0.0.13
name: package_fastx_toolkit_0_0_13
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/packages/package_fastx_toolkit_0_0_13
type: tool_dependency_definition
