categories:
- SAM
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  1.56.0 of the Picard package.
long_description: |
  This repository is intended to be defined as a complex repository
  dependency within a separate repository.
  http://wiki.galaxyproject.org/DefiningRepositoryDependencies#Complex_repository_dependencies:_tool_dependency_definitions_that_contain_repository_dependency_definitions
  Program: picard
  Version: 1.56.0
name: package_picard_1_56_0
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/packages/package_picard_1_56_0
type: tool_dependency_definition
