categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  1.0 of the galaxy operations python package.
long_description: |
  This repository is intended to be defined as a complex repository
  dependency within a separate repository.
  http://wiki.galaxyproject.org/DefiningRepositoryDependencies#Complex_repository_dependencies:_tool_dependency_definitions_that_contain_repository_dependency_definitions
  Library: galaxy-ops
  Version: 1.0.0
name: package_galaxy_ops_1_0_0
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/packages/package_galaxy_ops_1_0_0
type: tool_dependency_definition
