categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  1.7 of the the python numpy package
long_description: |
  This repository is intended to be defined as a complex repository
  dependency within a separate repository. 
  http://wiki.galaxyproject.org/DefiningRepositoryDependencies#Complex_repository_dependencies:_tool_dependency_definitions_that_contain_repository_dependency_definitions
name: package_numpy_1_7
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/packages/package_numpy_1_7
type: tool_dependency_definition
