categories:
- Data Managers
description: data_manager_picard_index_builder
homepage_url: ''
long_description: |
    data_manager_picard_index_builder
name: data_manager_picard_index_builder
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/data_managers/data_manager_picard_index_builder
type: unrestricted
