categories:
- Transcriptomics
description: Galaxy wrappers for the Cuffmerge tool.
homepage_url: http://cole-trapnell-lab.github.io/cufflinks/
name: cuffmerge
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/cufflinks/cuffmerge
type: unrestricted
