categories:
- Sequence Analysis
description: A tool for filtering on bamfiles
long_description: |
  Utility for filtering BAM files. It is based on BAMtools suite
  of tools by Derek Barnett.
homepage_url: https://github.com/pezmaster31/bamtools
name: bamtools_filter
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/bamtools/bamtools_filter
type: unrestricted
