categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and builds the Bioconductor
  qvalue R library.
long_description: |
  This repository is intended to be defined as a complex repository
  dependency within a separate repository.
  http://wiki.galaxyproject.org/DefiningRepositoryDependencies#Complex_repository_dependencies:_tool_dependency_definitions_that_contain_repository_dependency_definitions
  Library: qvalue
  Version: 1.34.0
name: package_bioc_qvalue_1_34_0
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/packages/package_bioc_qvalue_1_34_0
type: tool_dependency_definition
