categories:
- Sequence Analysis
description: A collection of tools for manipulation of bamfiles
long_description: |
  BAMTools is a collection of utilities for splitting BAM files.
  It is based on BAMtools suite of tools by Derek Barnett.
name: bamtools
owner: devteam
homepage_url: https://github.com/pezmaster31/bamtools
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/bamtools/bamtools
type: unrestricted
