categories:
- Transcriptomics
description: Galaxy wrappers for the Cuffdiff tool.
long_description: |
  Cuffdiff is part of Cufflinks. Cuffdiff find significant changes
  in transcript expression, splicing, and promoter use.
homepage_url: http://cole-trapnell-lab.github.io/cufflinks/
name: cuffdiff
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/cufflinks/cuffdiff
type: unrestricted
